# You can change this value to "de" to get the German translations.
# You can also create your own translations. Check the wiki for more info.
# If you made a new translation, I would appreciate if you could share it with the community!
language: en

prefix: "&3EasyConomy &8| &7"

enable-logging: true

update-checker: true

permissions:
  README: >
    IF YOU WANT THE PLUGIN TO USE PERMISSIONS,
    WRITE THE PERMISSIONS DOWN IN THE "".
    EMPTY QUOTATION MARKS => BALANCE AND OTHERSBALANCE AND PAY FOR EVERYONE
    AND MODIFY FOR OP ONLY
  balance: ""
  othersBalance: ""
  pay: ""
  modify: ""
  baltop: ""

startingBalance: 0

minimumTransactionAmount: 0.1
# All decimals shown
decimalsShown: -1

# Set to -1 to disable baltop.
baltopPlayers: 10

names:
  currencyNamePlural: "Dollars"
  currencyNameSingular: "Dollar"
  currencyFormatPlural: "%s Dollars"
  currencyFormatSingular: "%s Dollar"

# Do not change this value.
# This value makes sure that the config always updates when the plugin updates.
CONFIG_VERSION_NEVER_CHANGE_THIS: 4